version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: students_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: students
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: ./backend
    container_name: students_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: students
      PORT: 5000
    ports:
      - "50000:5000"

  web:
    image: nginx:alpine
    container_name: students_web
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./backend/static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
